namespace StopwatchCore
{
    [default_interface]
    [marshaling_behavior(agile)]
    [threading(both)]
    unsealed runtimeclass Stopwatch
    {
        Stopwatch();

        Double Duration{ get; };
        Windows.Foundation.TimeSpan Interval{ get; set; };
        StopwatchState State{ get; };

        Boolean Start();
        Boolean Pause();
        Boolean Resume();
        Boolean Stop();
        Boolean Reset();

        event Windows.Foundation.TypedEventHandler<Stopwatch, Object> Working;
    }

    enum StopwatchState
    {
        Stopped,
        Working,
        Paused
    };
}
